spring.application.name=finance-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://ep-broad-pine-am170jcu.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_tp0yze3crsoN

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true